trigger: none

stages:
# Stage 1 - Terraform Init
- stage: terraforminit
  displayName: Terraform Init
  jobs:
  - job: terraformInit
    displayName: Terraform Init Job
    pool:
      name: testingpool
    steps:
    - task: TerraformInstaller@1
      inputs:
        terraformVersion: 'latest'
    - task: TerraformTask@5
      inputs:
        provider: 'azurerm'
        command: 'init'
        backendServiceArm: 'azure connection'
        backendAzureRmOverrideSubscriptionID: 'e8ad8a11-5e89-4545-9309-27ed1a0cd62f'
        backendAzureRmResourceGroupName: 'satrg'
        backendAzureRmStorageAccountName: 'storage552'
        backendAzureRmContainerName: 'cont1'
        backendAzureRmKey: 're.tfstate'

# Stage 2 - Terraform Plan
- stage: terraformplan
  displayName: Terraform Plan
  jobs:
  - job: terraformPlan
    displayName: Terraform Plan Job
    pool:
      name: testingpool
    steps:
    - task: TerraformTask@5
      inputs:
        provider: 'azurerm'
        command: 'plan'
        environmentServiceNameAzureRM: 'azure connection'
        environmentAzureRmOverrideSubscriptionID: 'e8ad8a11-5e89-4545-9309-27ed1a0cd62f'

# Stage 3 - Terraform Apply
- stage: terraformapply
  displayName: Terraform Apply
  jobs:
  - job: terraformApply
    displayName: Terraform Apply Job
    pool:
      name: testingpool
    steps:
    - task: TerraformTask@5
      inputs:
        provider: 'azurerm'
        command: 'apply'
        environmentServiceNameAzureRM: 'azure connection'
        environmentAzureRmOverrideSubscriptionID: 'e8ad8a11-5e89-4545-9309-27ed1a0cd62f'
