trigger: none

pool: testingpool

stages:
- stage:terraforminit
displayName: terraform init
  pool: testingpool

jobs:
- job: terraform init
steps:
- task: TerraformInstaller@1
  inputs:
    terraformVersion: 'latest'
- task: TerraformTask@5
  inputs:
    provider: 'azurerm'
    command: 'init'
    backendServiceArm: 'azure connection'
    backendAzureRmOverrideSubscriptionID: 'e8ad8a11-5e89-4545-9309-27ed1a0cd62f'
    backendAzureRmResourceGroupName: 'satrg'
    backendAzureRmStorageAccountName: 'storage552'
    backendAzureRmContainerName: 'container'
    backendAzureRmKey: 're.tfstate'
- stage: terraformplan
  displayName: terraform plan
  pool: testingpool
  jobs:
- job: terraform plan
step:
- task: TerraformTask@5
  inputs:
    provider: 'azurerm'
    command: 'plan'
    environmentServiceNameAzureRM: 'azure connection'
    environmentAzureRmOverrideSubscriptionID: 'e8ad8a11-5e89-4545-9309-27ed1a0cd62f'
- stage:terraformapply
displayName: terraform apply
  pool: testingpool
jobs:
- job: terraform apply
steps:
- task: TerraformTask@5
  inputs:
    provider: 'azurerm'
    command: 'apply'
    environmentServiceNameAzureRM: 'azure connection'
    environmentAzureRmOverrideSubscriptionID: 'e8ad8a11-5e89-4545-9309-27ed1a0cd62f'